---
name: Chrome - CNN
author: Gladysfotsa <gladysfotsa99@gmail.com>
description: Benchmarking Chrome visiting CNN.com

architecture: Linux

services:
  chrome-container:
    image: yourdockerhubusername/chrome-container
    environment:
      URL_TO_VISIT: "https://www.cnn.com"
    command: /usr/local/bin/chrome-entry.sh

flow:
  - name: Load CNN
    container: chrome-container
    commands:
      - type: console
        command: sleep 30
